### ISSUE TITLE
Enable Firefox in test-ui stage

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/meetling#74]
Making use of advanced user interactions fails in Firefox with `remote error: UnsupportedOperationError: mouseMoveTo`. This problem is addressed both for the [Selenium Node.js client](https://github.com/SeleniumHQ/selenium/issues/4564) and the [Selenium server](https://github.com/SeleniumHQ/selenium/issues/3693) and either approach may fix it once implemented / deployed by Sauce Labs.

Travis CI config to enable Firefox:

```yaml
jobs:
    include:
        - <<: *test-ui
          env: BROWSER=firefox PLATFORM="Windows 10"
```
