### ISSUE TITLE
Enable Safari in test-ui stage

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/meetling#75]
Running the UI tests against Safari fails with a `QuotaExceededError`, due to [localStorage wongly being disabled](https://bugs.webkit.org/show_bug.cgi?id=157010) in a WebDriver session. This should be fixed in Safari 10.1, which is not yet available on Sauce Labs.

Travis CI config to enable Safari:

```yaml
jobs:
    include:
        - <<: *test-ui
          env: BROWSER=safari PLATFORM="macOS 10.12"
```
